name: flt_ulearning
description: "App for learning"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.0.dev <4.0.0'

dependencies:
  cached_network_image: null
  cloud_firestore: null
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  dots_indicator: ^3.0.0
  firebase_auth: null
  firebase_core: null
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  fluttertoast: null
  http: null
  riverpod_annotation: ^2.3.5
  shared_preferences: null

dev_dependencies:
  build_runner: null
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: null

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/voice/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400 # normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
