// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo0A9TrsTFEigl9gd-vCGEnye1JCkjLtQ',
    appId: '1:144919311575:web:e23e7284b1ac3610342c92',
    messagingSenderId: '144919311575',
    projectId: 'flt-ulearning',
    authDomain: 'flt-ulearning.firebaseapp.com',
    storageBucket: 'flt-ulearning.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNdiAjLy15-PkxpP2v9KH-aqfWq48kNsI',
    appId: '1:144919311575:android:0e73a6f0ee20b222342c92',
    messagingSenderId: '144919311575',
    projectId: 'flt-ulearning',
    storageBucket: 'flt-ulearning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1KW5aTWDifGnqOYUnNGV3IJc8fm1ZdfY',
    appId: '1:144919311575:ios:64b69a54d2d5060a342c92',
    messagingSenderId: '144919311575',
    projectId: 'flt-ulearning',
    storageBucket: 'flt-ulearning.appspot.com',
    iosBundleId: 'com.example.fltUlearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1KW5aTWDifGnqOYUnNGV3IJc8fm1ZdfY',
    appId: '1:144919311575:ios:66208ffc1cd5bdd1342c92',
    messagingSenderId: '144919311575',
    projectId: 'flt-ulearning',
    storageBucket: 'flt-ulearning.appspot.com',
    iosBundleId: 'com.example.fltUlearning.RunnerTests',
  );
}
